"""Hizmet sayfası metinlerini (services.content / services.faqs) üretir ve SQL'e çevirir.

Kullanım: python3 build_service_content.py tesisat > out.sql
Metinler gerçek işletme bilgisine dayanır: seyyar çalışma, Şırnak'ın 7 ilçesi,
tesisatta 7/24, masajda 09:00-21:00. Uydurma garanti/yıl/fiyat yazılmaz.
"""
import json, sys

ILCELER = "Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak"

def ul(items): return "\n".join(f"- {i}" for i in items)

def tesisat(s):
    n, k = s["name"], s["kw"]
    parts = [
        s["intro"],
        f"## Şırnak {n} Hizmeti Neleri Kapsar?",
        s["scope_intro"],
        ul(s["scope"]),
        f"## {s['when_title']}",
        s["when_intro"],
        ul(s["signs"]),
        s.get("when_outro", ""),
        f"## Şırnak {n} Nasıl Yapılır? Adım Adım Süreç",
        ul(s["steps"]),
        f"## Şırnak {n} Fiyatları Neye Göre Değişir?",
        f"{n} ücreti her evde aynı değildir; işin büyüklüğü yerinde görülmeden kesin rakam söylemek doğru olmaz. Fiyatı belirleyen başlıca etkenler şunlardır:",
        ul(s["price"]),
        "Telefonda ya da WhatsApp'tan sorunun fotoğrafını veya kısa bir videosunu gönderirseniz size ön bilgi verebiliriz; net ücret iş yerinde görüldükten sonra, işe başlamadan önce konuşulur.",
        "## Sık Yapılan Hatalar",
        ul(s["mistakes"]),
        f"## {n} Sonrası Dikkat Edilmesi Gerekenler",
        ul(s["after"]),
        f"## {k} İçin Şırnak'ın Tüm İlçelerine Geliyoruz",
        f"Çözüm Noktası olarak seyyar çalışıyoruz: aracımız ve ekipmanımızla {ILCELER} başta olmak üzere Şırnak'ın tüm ilçelerinde ev ve iş yerlerine geliyoruz. Acil durumlar için 7/24 ulaşabilirsiniz. Telefonla arayabilir veya WhatsApp'tan konum atarak en hızlı şekilde usta çağırabilirsiniz.",
    ]
    return "\n\n".join(p for p in parts if p)

T = [
 dict(slug="tikaniklik-acma", name="Tıkanıklık Açma", kw="Tıkanıklık Açma",
  intro="Lavabo yavaş akıyorsa, tuvalet taşıyorsa ya da mutfak giderinden kötü koku geliyorsa tıkanıklık büyümeden müdahale etmek gerekir. Şırnak'ta tıkanıklık açma hizmetimizle lavabo, mutfak, banyo, tuvalet ve logar tıkanıklıklarını robot ve kamera ile, fayans kırmadan açıyoruz. Seyyar çalıştığımız için aracımızla adresinize geliyor, sorunu yerinde tespit edip aynı ziyarette çözmeye çalışıyoruz.",
  scope_intro="Tıkanık açma tek bir işlem değildir; tıkanıklığın yeri ve sebebi her evde farklıdır. Bu hizmet kapsamında yaptığımız başlıca işler:",
  scope=["Lavabo ve banyo gideri tıkanıklığı açma","Mutfak gideri ve evye tıkanıklığı açma (yağ birikmesi dahil)","WC / klozet tıkanıklığı açma","Duş teknesi ve küvet gideri açma","Yer süzgeci ve balkon gideri açma","Bina ana gider hattı ve logar tıkanıklığı açma","Kamera ile tıkanıklık yerinin tespiti"],
  when_title="Ne Zaman Tıkanıklık Açma Gerekir?",
  when_intro="Aşağıdaki belirtilerden biri varsa giderde tıkanıklık başlamış olabilir:",
  signs=["Su lavabodan veya duştan geç çekiliyor","Giderden gurultu sesi geliyor","Lavabo, mutfak veya banyoda kötü koku var","Bir gider açıldığında başka bir giderden su geri geliyor","Tuvalet sifonu çekildiğinde su yükseliyor","Yer süzgecinden su taşıyor"],
  when_outro="Küçük bir yavaşlama zamanla tamamen tıkanmaya dönüşebilir. Erken müdahale hem masrafı hem de su hasarı riskini azaltır.",
  steps=["Telefon veya WhatsApp üzerinden sorunu dinliyor, adresinizi alıyoruz","Aracımızla adresinize geliyor, hangi giderin ne kadar tıkalı olduğuna bakıyoruz","Gerekirse kamera ile boru içini görüntüleyip tıkanıklığın yerini buluyoruz","Robot / yay makinesi ile tıkanıklığı kırmadan açıyoruz","Suyu akıtarak hattı test ediyor, akışın normale döndüğünü birlikte kontrol ediyoruz","Tekrar tıkanmaması için kullanım önerilerini paylaşıyoruz"],
  price=["Tıkanıklığın yeri (lavabo, mutfak, tuvalet veya ana hat)","Tıkanıklığın sebebi (yağ, saç, kireç, yabancı cisim, kök vb.)","Hat uzunluğu ve kamera ile tespit gerekip gerekmediği","Bina ana hattı veya logar çalışması olup olmadığı","Acil / gece çalışması gerekip gerekmediği"],
  mistakes=["Kimyasal gider açıcıları sık kullanmak: boruları ve contaları yıpratabilir, tıkanıklığı da tam açmaz","Tıkanık giderde sürekli su akıtmak: su başka noktalardan taşabilir","Tel, şiş gibi aletlerle zorlamak: boru içine takılabilir veya sifonu bozabilir","Sorunu ertelemek: küçük tıkanıklık zamanla ana hatta ilerleyebilir"],
  after=["Mutfak giderine yağ dökmeyin; yağı kurumaya bırakıp çöpe atın","Lavabo ve duş giderlerinde saç tutucu süzgeç kullanın","Tuvalete ıslak mendil, ped, pamuk gibi atıklar atmayın","Ayda bir giderlerden bol sıcak su geçirin"],
  faqs=[("Şırnak'ta tıkanıklık açma için kırma dökme gerekir mi?","Çoğu durumda gerekmez. Robot ve kamera ile tıkanıklığı boru içinden açıyoruz; fayans veya duvar kırmak ancak boru kırık ya da çökmüşse gündeme gelir ve bu durumda önce size bilgi veririz."),
        ("Tıkanıklık açma ne kadar sürer?","Basit lavabo ve mutfak tıkanıklıkları çoğunlukla kısa sürede açılır. Ana hat veya logar tıkanıklıklarında süre, hattın uzunluğuna ve tıkanıklığın sebebine göre uzayabilir."),
        ("Gece veya hafta sonu tıkanıklık için gelir misiniz?","Evet, tesisat arızaları için 7/24 ulaşabilirsiniz. Taşma gibi acil durumlarda önce ana vanayı kapatmanızı, ardından bizi aramanızı öneririz."),
        ("Cizre, Silopi veya İdil'e de geliyor musunuz?","Evet. Seyyar çalışıyoruz ve Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'taki adreslere aracımızla geliyoruz."),
        ("Tıkanıklık açma fiyatı ne kadar?","Fiyat tıkanıklığın yerine ve sebebine göre değişir. WhatsApp'tan fotoğraf veya video gönderirseniz ön bilgi veririz; net ücret yerinde görüldükten sonra işe başlamadan konuşulur."),
        ("Tıkanıklık sürekli tekrar ediyor, neden olabilir?","Sık tekrar eden tıkanıklıklar genellikle borudaki eğim hatası, kırık boru veya hatta biriken yağ tabakasından kaynaklanır. Kamera ile hattı inceleyerek kalıcı sebebi bulmaya çalışıyoruz.")]),
 dict(slug="wc-tikanikligi-acma", name="WC Tıkanıklığı Açma", kw="WC Açma",
  intro="Tuvaletin tıkanması evde en can sıkıcı arızalardan biridir ve beklemeye gelmez. Şırnak'ta WC tıkanıklığı açma hizmetimizle klozet ve tuvalet hattındaki tıkanıklıkları makine ile, kırmadan açıyoruz. Aracımızla adresinize geliyor, tuvaleti kısa sürede yeniden kullanılır hale getirmeye çalışıyoruz.",
  scope_intro="WC açma hizmeti kapsamında şu işleri yapıyoruz:",
  scope=["Klozet içi tıkanıklık açma","Tuvalet çıkış borusu ve bağlantı tıkanıklığı açma","Alaturka tuvalet tıkanıklığı açma","Tuvaletin bağlı olduğu ana gider hattının açılması","Gerektiğinde klozet söküp takma","Rezervuar ve sifon kaynaklı sorunların kontrolü"],
  when_title="WC Tıkanıklığının Belirtileri",
  when_intro="Şu durumlar tuvalet hattında tıkanıklık olduğunu gösterir:",
  signs=["Sifon çekince su yükseliyor veya geç iniyor","Klozetten gurultu sesi geliyor","Tuvalet kullanıldığında banyo süzgecinden su çıkıyor","Banyoda sürekli lağım kokusu var","Su tamamen çekilmiyor, klozette bekliyor"],
  when_outro="Su klozetin kenarına kadar yükseliyorsa sifonu tekrar çekmeyin; taşma olabilir.",
  steps=["Arızayı telefonda dinliyor, adresinize geliyoruz","Tıkanıklığın klozette mi yoksa hatta mı olduğunu tespit ediyoruz","Uygun makine ve uçla tıkanıklığı kırmadan açıyoruz","Gerekirse klozeti söküp çıkış borusunu temizliyoruz","Birkaç kez sifon çekerek hattı test ediyoruz"],
  price=["Tıkanıklığın klozette mi ana hatta mı olduğu","Klozetin sökülmesinin gerekip gerekmediği","Tıkanıklığa sebep olan cismin türü","Acil / gece çalışması"],
  mistakes=["Tıkalıyken üst üste sifon çekmek","Klozete kimyasal veya kostik dökmek: porselene ve contalara zarar verebilir","Pompa ile çok sert zorlamak: bağlantı yerlerinden kaçak oluşabilir"],
  after=["Tuvalete ıslak mendil, ped, bebek bezi, pamuk ve kâğıt havlu atmayın","Tuvalet kâğıdını aşırı miktarda kullanmaktan kaçının","Çocukların oyuncak gibi cisimleri atmasına dikkat edin"],
  faqs=[("WC tıkanıklığı kırmadan açılır mı?","Evet, tuvalet tıkanıklıklarının büyük çoğunluğu makine ile kırmadan açılır. Kırma ancak boru hasarlıysa gerekir ve önce size danışırız."),
        ("Tuvalete düşen cisim çıkarılabilir mi?","Çoğu durumda evet. Gerekirse klozeti söküp cismi çıkarıyor ve tekrar sıfır sızdırmaz şekilde takıyoruz."),
        ("WC açma için gece gelir misiniz?","Evet, 7/24 ulaşabilirsiniz."),
        ("Hangi ilçelere geliyorsunuz?","Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'a geliyoruz.")]),
 dict(slug="gider-acma", name="Mutfak ve Lavabo Gideri Açma", kw="Gider Açma",
  intro="Mutfak gideri ve lavabo tıkanıklıkları genellikle zamanla biriken yağ, sabun, saç ve kireç yüzünden oluşur. Şırnak'ta gider açma hizmetimizle mutfak evyesi, banyo lavabosu, duş ve yer süzgeci giderlerini kırmadan açıyoruz. Seyyar çalışıyor, aracımızla adresinize geliyoruz.",
  scope_intro="Gider açma hizmetimiz şunları kapsar:",
  scope=["Mutfak gideri açma (yağ ve yemek artığı birikmesi)","Lavabo gideri ve sifon temizliği","Banyo, duş ve küvet gideri açma","Yer süzgeci ve balkon gideri açma","Bulaşık ve çamaşır makinesi gider hattı açma","Sifon, gider borusu ve conta değişimi"],
  when_title="Gider Tıkanıklığı Ne Zaman Ustaya Gösterilmeli?",
  when_intro="Şu belirtiler giderin tıkanmaya başladığını gösterir:",
  signs=["Evyede su birikiyor ve geç çekiliyor","Bulaşık makinesi suyu boşaltmıyor","Lavabodan kötü koku geliyor","Sifondan su sızıyor","Yer süzgecinden su geri geliyor"],
  steps=["Hangi giderin tıkalı olduğunu ve diğer giderlerin durumunu kontrol ediyoruz","Önce sifonu söküp temizliyoruz","Tıkanıklık sifondan sonraysa makine ile boru hattını açıyoruz","Gerekirse kamera ile hattı inceliyoruz","Suyu akıtıp sızdırmazlığı kontrol ediyoruz"],
  price=["Tıkanıklığın sifonda mı hatta mı olduğu","Yağ birikmesinin yoğunluğu","Hat uzunluğu","Parça (sifon, conta, boru) değişimi gerekip gerekmediği"],
  mistakes=["Sıcak yağı evyeye dökmek: soğuyunca boruda donar","Sürekli kimyasal açıcı kullanmak","Sifonu yanlış takıp sızıntıya yol açmak"],
  after=["Evyede süzgeç kullanın, yemek artıklarını çöpe atın","Yağlı tavaları yıkamadan önce kâğıtla silin","Haftada bir giderden kaynar su geçirin"],
  faqs=[("Mutfak gideri neden sık tıkanır?","En yaygın sebep yağdır. Sıcakken akan yağ boruda soğuyup katılaşır, yemek artıklarını tutar ve zamanla tıkanıklık oluşturur."),
        ("Gider açma ne kadar sürer?","Sifon kaynaklı tıkanıklıklar kısa sürede çözülür; hattaki yağ birikmesi daha uzun sürebilir."),
        ("Gider açarken boru değişimi gerekir mi?","Genellikle hayır. Boru kırık, çatlak veya eğimi hatalıysa değişim önerir, önce size bilgi veririz."),
        ("Bulaşık makinesi su boşaltmıyor, gelir misiniz?","Evet. Makinenin bağlı olduğu gider hattı tıkalıysa açıyoruz; makinenin kendi pompası arızalıysa bunu size söyleriz.")]),
 dict(slug="su-kacagi-tespiti", name="Su Kaçağı ve Su Sızıntısı Tespiti", kw="Su Kaçağı Tespiti",
  intro="Su faturanız sebepsiz yere yükseldiyse, duvarda nem lekesi, kabarma ya da küf oluştuysa veya alt kattan sızıntı şikâyeti geldiyse tesisatta su kaçağı olabilir. Şırnak'ta su kaçağı ve su sızıntısı tespiti hizmetimizle kaçağın yerini bulup tamirini yapıyoruz. Amacımız gereksiz kırma yapmadan, sadece sorunlu noktaya müdahale etmektir.",
  scope_intro="Su kaçağı tespiti ve tamiri kapsamında:",
  scope=["Temiz su hattında kaçak tespiti","Banyo, mutfak ve tuvalet kaynaklı sızıntı tespiti","Duvar içi ve zemin altı boru kaçakları","Kalorifer ve kombi tesisatında su kaybı","Alt kata su sızdırma şikâyetlerinin kaynağının bulunması","Tespit edilen noktada boru ve bağlantı tamiri"],
  when_title="Su Kaçağı Olduğunu Nasıl Anlarsınız?",
  when_intro="Su kaçağı çoğu zaman gözle görülmez; şu belirtilere dikkat edin:",
  signs=["Su faturası kullanımınıza göre yüksek geliyor","Tüm musluklar kapalıyken su sayacı dönüyor","Duvarda, tavanda veya zeminde nem lekesi, kabarma, küf","Fayans derzlerinde kararma, parkede kabarma","Alt kattaki komşudan sızıntı şikâyeti","Kombi basıncı sürekli düşüyor"],
  when_outro="Basit bir kontrol: Evdeki tüm muslukları ve cihazları kapatıp su sayacına bakın. Sayaç hâlâ dönüyorsa hatta kaçak olma ihtimali yüksektir.",
  steps=["Belirtileri ve sayaç durumunu dinliyoruz","Yerinde hat kontrolü yaparak kaçağın hangi bölgede olduğunu daraltıyoruz","Kaçak noktasını tespit edip size gösteriyoruz","Sadece gerekli noktayı açarak boru veya bağlantıyı tamir ediyoruz","Hattı basınçla test edip kaçağın giderildiğini kontrol ediyoruz"],
  price=["Kaçağın bulunduğu yer (duvar içi, zemin altı, tavan)","Kaçağın temiz su mu, kalorifer hattı mı olduğu","Açılması gereken alanın büyüklüğü","Boru ve bağlantı parçası ihtiyacı"],
  mistakes=["Nem lekesini sadece boyayla kapatmak","Kaçağı uzun süre ihmal etmek: duvar, zemin ve alt kat zarar görür","Kaçağın yerini bilmeden rastgele kırmak"],
  after=["Su sayacını ayda bir kontrol edin","Ana vananın yerini bilin, acil durumda hemen kapatın","Eski tesisatlarda birkaç yılda bir genel kontrol yaptırın"],
  faqs=[("Su kaçağı kırmadan bulunur mu?","Kaçağın yeri büyük ölçüde kırmadan tespit edilir. Tamir için çoğu zaman sadece kaçak olan küçük bir alanın açılması gerekir."),
        ("Su faturam çok yüksek geldi, kaçak mı var?","Olabilir. Tüm muslukları kapatıp sayacı kontrol edin; sayaç dönüyorsa bizi arayın."),
        ("Alt kata su sızıyor, ne yapmalıyım?","Önce sızıntının hangi tesisattan geldiğini bulmak gerekir: banyo gideri, temiz su borusu veya kalorifer hattı olabilir. Yerinde kontrol ederek kaynağı tespit ediyoruz."),
        ("Su sızıntısı ile su kaçağı arasında fark var mı?","Halk arasında ikisi de aynı anlamda kullanılır. Genellikle sızıntı daha yavaş ve damla damla olan, kaçak ise hatta sürekli su kaybı olan durum için söylenir; ikisinin de tespiti aynı şekilde yapılır."),
        ("Hangi ilçelerde su kaçağı tespiti yapıyorsunuz?","Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'ta hizmet veriyoruz.")]),
 dict(slug="su-tesisati", name="Su Tesisatı (Sucu & Muslukçu)", kw="Sucu ve Muslukçu",
  intro="Damlayan musluk, değiştirilmesi gereken batarya, yenilenecek boru hattı ya da sıfırdan kurulacak su tesisatı... Şırnak'ta sucu ve muslukçu ihtiyacınız için Çözüm Noktası olarak aracımızla adresinize geliyoruz. Küçük tamirlerden komple su tesisatı yenilemeye kadar tüm su tesisatı işlerini yapıyoruz.",
  scope_intro="Su tesisatı hizmetlerimiz:",
  scope=["Musluk, batarya ve armatür değişimi / tamiri","Damlayan musluk ve conta değişimi","Lavabo, evye ve klozet montajı","Rezervuar tamiri ve iç takım değişimi","Ara musluk, vana ve ana vana değişimi","Eski boruların yenilenmesi, sıfırdan su tesisatı","Su deposu ve hidrofor bağlantıları","Çamaşır ve bulaşık makinesi su bağlantısı"],
  when_title="Ne Zaman Sucu / Muslukçu Çağırmalısınız?",
  when_intro="Şu durumlarda su tesisatçısına ihtiyaç vardır:",
  signs=["Musluk veya batarya damlatıyor","Su basıncı düştü, musluktan az su geliyor","Rezervuar sürekli su akıtıyor","Vana kapanmıyor veya sızdırıyor","Borularda paslanma, renkli su","Yeni ev veya tadilatta tesisat kurulması gerekiyor"],
  steps=["İhtiyacınızı dinliyor, gerekiyorsa fotoğraf istiyoruz","Adresinize gelip yerinde kontrol ediyoruz","Gerekli parçalar ve işçilik için bilgi veriyoruz","Montaj veya tamiri yapıyoruz","Suyu açıp sızdırmazlık kontrolü yapıyoruz"],
  price=["İşin türü (musluk değişimi, boru yenileme, komple tesisat)","Kullanılacak malzemenin cinsi ve markası","Duvar içi çalışma gerekip gerekmediği","İşin metrajı ve süresi"],
  mistakes=["Damlayan musluğu ihmal etmek: ayda ciddi miktarda su boşa gider","Vanaları aşırı sıkmak: conta ve diş zarar görür","Kalitesiz bağlantı parçası kullanmak"],
  after=["Ana vananın ve ara muslukların yerini bilin","Uzun süre evden ayrılacaksanız ana vanayı kapatın","Kış aylarında açıkta kalan boruları donmaya karşı yalıtın"],
  faqs=[("Sadece musluk değişimi için de geliyor musunuz?","Evet, küçük işler için de geliyoruz. Musluk, batarya, conta ve vana değişimi gibi işleri yerinde yapıyoruz."),
        ("Malzemeyi siz mi getiriyorsunuz?","İsterseniz malzemeyi biz getiriyoruz, isterseniz kendi aldığınız ürünü monte ediyoruz."),
        ("Eski evde boruların hepsi değişmeli mi?","Her zaman değil. Borular yerinde kontrol edilir; sadece sorunlu bölümün değişmesi yeterli olabilir."),
        ("Su basıncı düşük, ne yapılabilir?","Basınç düşüklüğü kireçlenme, vana arızası, boru kaçağı veya şebeke kaynaklı olabilir. Yerinde kontrol edip sebebe göre çözüm öneriyoruz.")]),
 dict(slug="kombi-tamiri", name="Kombi Tamiri", kw="Kombi Tamiri",
  intro="Kombiniz sıcak su vermiyor, petekleri ısıtmıyor, su akıtıyor ya da sürekli arıza kodu veriyorsa kombi tamiri gerekir. Şırnak'ta kombi tamiri hizmetimizle arızayı yerinde tespit ediyor, uygun çözümü sunuyoruz. Özellikle kış aylarında bekletmemek için aracımızla adresinize geliyoruz.",
  scope_intro="Kombi tamiri kapsamında karşılaştığımız başlıca arızalar:",
  scope=["Kombinin hiç çalışmaması / ateşleme yapmaması","Sıcak su gelmemesi veya ılık gelmesi","Peteklerin ısınmaması","Basıncın sürekli düşmesi veya yükselmesi","Kombiden su damlaması / akıtma","Kombinin sık sık kapanması, arıza kodu vermesi","Kombiden ses gelmesi"],
  when_title="Kombi Arızasının Belirtileri",
  when_intro="Şu durumlarda kombinizi kontrol ettirmeniz gerekir:",
  signs=["Ekranda arıza kodu veya yanıp sönen ışık","Basınç göstergesi 1 bar'ın altına düşüyor","Kombiden tıkırtı, uğultu veya kaynama sesi","Altında su birikintisi","Doğalgaz faturası beklenenden yüksek"],
  when_outro="Kombiden gaz kokusu alıyorsanız kombiyi kapatın, gaz vanasını kapatın, pencereleri açın, elektrik düğmelerine dokunmayın ve 187 Doğalgaz Acil'i arayın.",
  steps=["Arıza kodunu ve belirtileri telefonda dinliyoruz","Adresinize gelip kombiyi yerinde kontrol ediyoruz","Arızalı parçayı tespit edip size bilgi veriyoruz","Onayınızla tamiri yapıyoruz","Kombiyi çalıştırıp sıcak su ve kalorifer testini yapıyoruz"],
  price=["Arızanın türü ve değişmesi gereken parça","Kombinin markası ve modeli (yedek parça bulunabilirliği)","Ek olarak bakım veya petek temizliği gerekip gerekmediği"],
  mistakes=["Basınç düştükçe sürekli su basmak: tesisatta kaçak varsa sorun büyür","Arıza kodunu görmezden gelip kombiyi tekrar tekrar resetlemek","Gaz kokusuna rağmen kombiyi kurcalamak"],
  after=["Yılda bir kombi bakımı yaptırın","Basıncı 1–1,5 bar arasında tutun","Kombinin bulunduğu yerin havalandırmasını kapatmayın"],
  faqs=[("Kombi basıncı sürekli düşüyor, neden?","Genellikle tesisatta küçük bir su kaçağı, emniyet ventilinin su atması veya genleşme tankı sorunu vardır. Yerinde kontrol ederek sebebi buluyoruz."),
        ("Kombi sıcak su vermiyor ama petekler ısınıyor, neden olur?","Çoğunlukla üç yollu vana, akış sensörü veya plakalı eşanjör kaynaklıdır. Kombiyi açıp kontrol etmek gerekir."),
        ("Kombi tamiri ne kadar sürer?","Parça mevcutsa birçok arıza aynı ziyarette giderilir. Parça sipariş gerekiyorsa size süre konusunda bilgi veririz."),
        ("Garanti süresi devam eden kombiye bakıyor musunuz?","Garantisi devam eden kombilerde önce yetkili servisi aramanızı öneririz; garantinin bozulmaması için bu önemlidir."),
        ("Hangi ilçelerde kombi tamiri yapıyorsunuz?","Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'a geliyoruz.")]),
 dict(slug="kombi-bakimi", name="Kombi Bakımı", kw="Kombi Bakımı",
  intro="Düzenli kombi bakımı hem kombinizin ömrünü uzatır hem de kışın beklenmedik arızaların önüne geçer. Şırnak'ta kombi bakımı hizmetimizle kombinizi sezon başında temizliyor, ayarlarını kontrol ediyor ve olası sorunları önceden tespit ediyoruz.",
  scope_intro="Kombi bakımında yaptığımız kontroller:",
  scope=["Yanma odası ve brülör temizliği","Eşanjör kontrolü ve temizliği","Fan ve baca bağlantısı kontrolü","Genleşme tankı basınç kontrolü","Su filtresi temizliği","Tesisat basıncı ve emniyet ventili kontrolü","Gaz bağlantısında sızdırmazlık kontrolü","Genel çalışma ve verim testi"],
  when_title="Kombi Bakımı Ne Zaman Yapılmalı?",
  when_intro="Kombi bakımı için en doğru zaman ısıtma sezonu başlamadan önce, yani sonbahar aylarıdır. Şu durumlarda ise bakım ertelenmemelidir:",
  signs=["Son bakımın üzerinden bir yıldan fazla geçti","Kombi eskisine göre daha geç ısıtıyor","Doğalgaz faturası arttı","Kombiden ses geliyor","Petekler eşit ısınmıyor"],
  steps=["Randevu saatinde adresinize geliyoruz","Kombiyi kapatıp gerekli parçaları söküyoruz","Temizlik ve kontrolleri yapıyoruz","Basınç ve ayarları yapıp kombiyi çalıştırıyoruz","Gerekirse petek temizliği veya tamir önerisi sunuyoruz"],
  price=["Kombinin tipi ve modeli","Ek temizlik (eşanjör sökümü vb.) gerekip gerekmediği","Değişmesi gereken parça olup olmadığı","Bakımla birlikte petek yıkama yapılıp yapılmayacağı"],
  mistakes=["Kombi sadece arıza verince ilgilenmek","Bakımı kış ortasına bırakmak","Petek temizliğini hiç yaptırmamak"],
  after=["Basınç değerini ayda bir kontrol edin","Petek vanalarını yaz aylarında da birkaç kez açıp kapatın","Kombinin üstüne ve çevresine eşya koymayın"],
  faqs=[("Kombi bakımı yılda kaç kez yapılmalı?","Yılda bir kez, tercihen ısıtma sezonu başlamadan yapılması yeterlidir."),
        ("Kombi bakımı ne kadar sürer?","Kombinin durumuna göre değişmekle birlikte genellikle aynı ziyarette tamamlanır."),
        ("Kombi bakımı faturayı düşürür mü?","Temiz ve doğru ayarlanmış bir kombi daha verimli çalışır; bu da gaz tüketimine olumlu yansır."),
        ("Bakım ile birlikte petek temizliği de yapıyor musunuz?","Evet, isterseniz aynı ziyarette petek yıkama da yapıyoruz.")]),
 dict(slug="petek-temizligi", name="Petek Yıkama (Petek Temizliği)", kw="Petek Yıkama",
  intro="Kombi çalıştığı halde petekleriniz ısınmıyor, peteklerin üstü sıcak altı soğuksa tesisatın içinde çamur ve tortu birikmiş olabilir. Şırnak'ta petek yıkama hizmetimizle kalorifer tesisatını makine ile temizliyor, peteklerin yeniden eşit ısınmasını sağlıyoruz.",
  scope_intro="Petek temizliği kapsamında:",
  scope=["Makine ile tüm tesisatın ve peteklerin yıkanması","Tesisattaki çamur, pas ve tortunun temizlenmesi","Peteklerin havasının alınması","Gerekirse koruyucu kimyasal (inhibitör) uygulanması","Kombi filtresinin temizlenmesi","Temizlik sonrası basınç ayarı ve ısınma testi"],
  when_title="Petekler Ne Zaman Yıkanmalı?",
  when_intro="Şu belirtiler petek temizliği gerektiğini gösterir:",
  signs=["Peteklerin üst kısmı sıcak, alt kısmı soğuk","Bazı odalar ısınırken bazıları ısınmıyor","Kombi uzun süre çalıştığı halde ev geç ısınıyor","Doğalgaz faturası arttı","Peteklerden su sesi veya tıkırtı geliyor"],
  steps=["Peteklerin ısınma durumunu kontrol ediyoruz","Makineyi tesisata bağlayıp tüm hattı yıkıyoruz","Petekleri tek tek ya da toplu temizliyoruz","Havasını alıp sistemi tekrar dolduruyoruz","Kombiyi çalıştırıp tüm peteklerin ısındığını kontrol ediyoruz"],
  price=["Evdeki petek sayısı","Tesisatın kirlilik durumu","Koruyucu kimyasal uygulanıp uygulanmayacağı","Kombi bakımı ile birlikte yapılıp yapılmadığı"],
  mistakes=["Petek havasını almakla sorunun çözüldüğünü düşünmek","Yıllarca petek temizliği yaptırmamak","Tesisata sürekli taze su basmak (yeni tortu oluşur)"],
  after=["Petek temizliğini 2–3 yılda bir tekrarlayın","Isınma sezonu başında peteklerin havasını alın","Basınç düşüyorsa nedenini araştırın"],
  faqs=[("Petek yıkama gerçekten fark eder mi?","Tesisatta çamur birikmişse evet; temizlik sonrası peteklerin alt kısımları da ısınmaya başlar ve ev daha çabuk ısınır."),
        ("Petek temizliği evi kirletir mi?","Makine ile kapalı devre çalışıyoruz; çalışma alanını korumaya özen gösteriyoruz."),
        ("Petek yıkama ne kadar sürer?","Petek sayısına ve kirliliğe bağlı olarak değişir; çoğu evde aynı gün içinde tamamlanır."),
        ("Petek temizliği ne sıklıkla yapılmalı?","Genellikle 2–3 yılda bir yapılması önerilir; ısınma sorunu varsa daha erken yapılabilir.")]),
 dict(slug="termosifon-montaji", name="Termosifon Montajı", kw="Termosifon Montajı",
  intro="Yeni termosifon aldınız, eskisini değiştirmek ya da yerini değiştirmek istiyorsunuz... Şırnak'ta termosifon montajı hizmetimizle termosifonu duvara güvenli şekilde sabitliyor, su ve elektrik bağlantılarını yapıp çalışır şekilde teslim ediyoruz.",
  scope_intro="Termosifon hizmetlerimiz:",
  scope=["Yeni termosifon montajı","Eski termosifonun sökülmesi","Termosifon yer değişikliği","Su giriş-çıkış bağlantıları ve emniyet ventili montajı","Elektrik bağlantısı","Termosifon rezistans ve termostat değişimi","Termosifon bakımı ve kireç temizliği"],
  when_title="Termosifonda Ne Zaman Usta Gerekir?",
  when_intro="Şu durumlarda termosifon ustasına ihtiyacınız olur:",
  signs=["Yeni termosifon alındı","Su ısınmıyor veya çok geç ısınıyor","Termosifon su damlatıyor","Sigorta atıyor","Termosifondan ses geliyor (kireçlenme)"],
  steps=["Termosifonun kurulacağı duvarı ve tesisatı kontrol ediyoruz","Duvara uygun dübel ve askı ile sabitliyoruz","Su giriş ve çıkış bağlantılarını emniyet ventili ile yapıyoruz","Termosifonu suyla doldurup elektrik bağlantısını yapıyoruz","Isıtma ve sızdırmazlık testini yapıyoruz"],
  price=["Yeni montaj mı, söküp takma mı olduğu","Duvarın yapısı ve askı ihtiyacı","Ek boru, vana veya elektrik hattı gerekip gerekmediği","Rezistans / termostat gibi parça değişimi"],
  mistakes=["Termosifonu suyla doldurmadan elektriğe bağlamak: rezistans yanar","Emniyet ventilini takmamak","Zayıf duvara uygun olmayan dübelle asmak"],
  after=["Yılda bir kireç temizliği ve magnezyum anot kontrolü yaptırın","Uzun süre kullanmayacaksanız elektriğini kesin","Termostatı çok yüksek derecede tutmayın"],
  faqs=[("Termosifon montajı ne kadar sürer?","Hazır tesisata standart montaj genellikle kısa sürede tamamlanır; yer değişikliğinde süre uzayabilir."),
        ("Termosifonu siz mi getiriyorsunuz?","Genelde müşterinin aldığı cihazı monte ediyoruz; isterseniz malzeme konusunda yardımcı oluruz."),
        ("Termosifon ısıtmıyor, tamir edilir mi?","Çoğunlukla rezistans veya termostat arızasıdır ve değiştirilerek tamir edilir."),
        ("Hangi ilçelerde termosifon montajı yapıyorsunuz?","Şırnak'ın tüm ilçelerine geliyoruz.")]),
 dict(slug="elektrik-arizasi", name="Elektrik Arızası", kw="Elektrikçi",
  intro="Sigorta sürekli atıyor, prizlerden elektrik gelmiyor, ışıklar titriyor ya da yanık kokusu alıyorsanız elektrik tesisatında arıza olabilir. Şırnak'ta elektrikçi hizmetimizle arızayı yerinde tespit edip güvenli şekilde gideriyoruz. Acil elektrik arızaları için 7/24 ulaşabilirsiniz.",
  scope_intro="Elektrik hizmetlerimiz:",
  scope=["Elektrik arıza tespiti ve onarımı","Sigorta ve kaçak akım rölesi değişimi","Priz, anahtar ve duy değişimi","Avize, aplik ve aydınlatma montajı","Kablo çekimi ve hat yenileme","Sigorta panosu düzenleme","Termosifon, ocak ve klima elektrik hattı"],
  when_title="Ne Zaman Elektrikçi Çağırmalısınız?",
  when_intro="Şu durumlar elektrik tesisatında sorun olduğunu gösterir:",
  signs=["Sigorta veya kaçak akım rölesi sık sık atıyor","Prizlerden elektrik gelmiyor","Işıklar titriyor veya kararıyor","Priz veya pano çevresinde yanık kokusu, kararma","Prizler ısınıyor","Elektrik çarpması hissediliyor"],
  when_outro="Yanık kokusu, duman veya kıvılcım varsa sigortayı indirin ve tesisata dokunmadan hemen bizi arayın.",
  steps=["Arızayı telefonda dinleyip acil durumu değerlendiriyoruz","Adresinize gelip panoyu ve hatları kontrol ediyoruz","Arızalı hattı veya malzemeyi tespit ediyoruz","Güvenli şekilde onarım veya değişim yapıyoruz","Tüm hatları test ederek teslim ediyoruz"],
  price=["Arızanın yeri ve tespit süresi","Değişecek malzeme (sigorta, kablo, priz vb.)","Duvar içi kablo değişimi gerekip gerekmediği","Acil / gece çalışması"],
  mistakes=["Atan sigortayı sebebini bulmadan tekrar tekrar kaldırmak","Daha yüksek amperli sigorta takmak","Uzatma kablolarına aşırı yük bağlamak"],
  after=["Kaçak akım rölesini ayda bir test düğmesiyle kontrol edin","Eski evlerde tesisatı kontrol ettirin","Islak zeminde elektrikli cihaz kullanmayın"],
  faqs=[("Sigorta sürekli atıyor, neden?","Aşırı yük, kısa devre veya kaçak akım olabilir. Hangi hatta olduğunu tespit ederek kalıcı çözüm buluyoruz."),
        ("Gece elektrik arızası için gelir misiniz?","Evet, acil elektrik arızaları için 7/24 ulaşabilirsiniz."),
        ("Avize ve aydınlatma montajı yapıyor musunuz?","Evet, avize, aplik, spot ve LED aydınlatma montajı yapıyoruz."),
        ("Hangi ilçelere elektrikçi olarak geliyorsunuz?","Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'a geliyoruz.")]),
 dict(slug="dogalgaz-tesisati", name="Doğalgaz Tesisatı", kw="Doğalgaz Tesisatı",
  intro="Doğalgaz tesisatında yapılacak her işlem güvenlik açısından titizlik gerektirir. Şırnak'ta doğalgaz tesisatı ile ilgili ocak ve kombi bağlantıları, sızdırmazlık kontrolleri ve tesisat düzenlemeleri konusunda destek veriyoruz.",
  scope_intro="Bu başlık altında verdiğimiz hizmetler:",
  scope=["Ocak ve soba bağlantısı","Kombi gaz bağlantısı kontrolü","Gaz hattında sızdırmazlık kontrolü","Esnek bağlantı hortumu değişimi","Tesisat ve vana kontrolü"],
  when_title="Doğalgaz Tesisatında Ne Zaman Kontrol Gerekir?",
  when_intro="Şu durumlarda tesisatınızı kontrol ettirin:",
  signs=["Ocak veya kombi yeni takılacak / yeri değişecek","Bağlantı hortumu eskidi veya çatladı","Vana zor açılıp kapanıyor","Ocak alevi düzensiz yanıyor"],
  when_outro="Gaz kokusu alırsanız: elektrik düğmelerine dokunmayın, ateş yakmayın, gaz vanasını kapatın, pencereleri açın ve 187 Doğalgaz Acil'i arayın. Yeni doğalgaz projesi ve gaz açma işlemleri dağıtım şirketinin yetkilendirdiği firmalar tarafından yapılır.",
  steps=["İhtiyacı ve tesisatın durumunu dinliyoruz","Yerinde kontrol yapıyoruz","Bağlantı veya değişim işlemini yapıyoruz","Sızdırmazlık testini yapıyoruz"],
  price=["İşin türü (bağlantı, hortum değişimi, kontrol)","Kullanılacak malzeme","Çalışma süresi"],
  mistakes=["Gaz bağlantısını kendi başına yapmaya çalışmak","Eski veya standart dışı hortum kullanmak","Gaz kokusunu önemsememek"],
  after=["Bağlantı hortumlarını süresi dolmadan değiştirin","Cihaz kullanılmadığında vanayı kapatın","Gaz alarm cihazı kullanmayı düşünün"],
  faqs=[("Ocak bağlantısı yapıyor musunuz?","Evet, ocak ve soba bağlantısı ile esnek hortum değişimi yapıyoruz."),
        ("Yeni doğalgaz projesi yapıyor musunuz?","Yeni abonelik projesi ve gaz açma işlemleri dağıtım şirketinin yetkili firmaları tarafından yapılır; bu konuda size yol gösterebiliriz."),
        ("Gaz kokusu alıyorum, ne yapmalıyım?","Hemen gaz vanasını kapatın, pencereleri açın, elektrik düğmelerine dokunmayın ve 187'yi arayın.")]),
 dict(slug="komple-tadilat", name="Komple Tadilat", kw="Banyo ve Mutfak Tadilatı",
  intro="Banyonuzu ya da mutfağınızı yenilemek, eski tesisatı tamamen değiştirmek istiyorsanız tesisat, elektrik ve uygulama işlerini tek elden planlamak işi kolaylaştırır. Şırnak'ta banyo, mutfak ve ev tadilatı için yerinde keşif yapıp ihtiyacınıza göre çözüm sunuyoruz.",
  scope_intro="Tadilat kapsamında:",
  scope=["Banyo tadilatı ve tesisat yenileme","Mutfak tadilatı, evye ve tezgah tesisatı","Komple su ve gider tesisatı yenileme","Elektrik tesisatı yenileme","Vitrifiye (klozet, lavabo, duşakabin) montajı","Fayans, seramik ve boya işlerinin koordinasyonu"],
  when_title="Ne Zaman Tadilat Düşünülmeli?",
  when_intro="Şu durumlarda tadilat en mantıklı çözüm olabilir:",
  signs=["Tesisat çok eski ve sık arıza veriyor","Banyo veya mutfakta sürekli nem ve sızıntı var","Yeni ev alındı ve yenilenmesi gerekiyor","Vitrifiye ve armatürler eskidi"],
  steps=["Yerinde keşif yapıp ihtiyaçlarınızı dinliyoruz","İşin kapsamını ve süresini birlikte planlıyoruz","Söküm ve tesisat altyapısını hazırlıyoruz","Uygulama ve montajları yapıyoruz","Test ve son kontrolle teslim ediyoruz"],
  price=["Tadilat yapılacak alanın büyüklüğü","Seçilen malzemeler","Tesisatın tamamen mi kısmen mi yenileneceği","İşin süresi"],
  mistakes=["Tesisatı yenilemeden sadece fayans değiştirmek","Planlama yapmadan işe başlamak","Kalitesiz bağlantı malzemesi kullanmak"],
  after=["Silikon ve derzleri düzenli kontrol edin","İlk haftalarda bağlantı noktalarında sızıntı olup olmadığına bakın"],
  faqs=[("Tadilat için keşif yapıyor musunuz?","Evet, yerinde görüp ihtiyacınızı dinledikten sonra kapsam ve süre hakkında bilgi veriyoruz."),
        ("Sadece banyo tesisatını yeniletebilir miyim?","Evet, tadilatın tamamını değil sadece tesisat kısmını da yapıyoruz."),
        ("Hangi ilçelerde tadilat yapıyorsunuz?","Şırnak'ın tüm ilçelerinde çalışıyoruz.")]),
]

def masaj(s):
    n, k = s["name"], s["kw"]
    parts = [
        s["intro"],
        f"## {n} Nedir?",
        s["what"],
        f"## Kimler İçin Uygundur?",
        ul(s["for"]),
        s.get("caution", ""),
        f"## Şırnak'ta {n} Nasıl Uygulanır?",
        ul(s["steps"]),
        "## Seans Öncesi ve Sonrası Öneriler",
        ul(s["tips"]),
        f"## {k}: Eve Gelen Masör ile Adresinizde",
        f"Doğal Dokunuş olarak salonumuz yok; seyyar çalışıyoruz. Randevu verdiğiniz saatte {ILCELER} başta olmak üzere Şırnak'ın tüm ilçelerinde evinize geliyoruz. Çalışma saatlerimiz 09:00–21:00 arasıdır. Randevu ve bilgi için arayabilir ya da WhatsApp'tan yazabilirsiniz.",
    ]
    return "\n\n".join(p for p in parts if p)

DOCTOR = "Önemli: Masaj tıbbi tedavinin yerine geçmez. Tanı konmuş bir rahatsızlığınız varsa masaj öncesinde doktorunuza danışmanızı öneririz. Şiddetli ağrı, uyuşma, güç kaybı veya idrar-dışkı kontrolünde sorun varsa masaj yerine vakit kaybetmeden doktora başvurun."
M = [
 dict(slug="rahatlama-masaji", name="Rahatlama ve Dinlenme Masajı", kw="Rahatlama Masajı",
  intro="Yoğun iş temposu, uzun süre ayakta kalmak ya da gün boyu masa başında oturmak vücutta gerginlik ve yorgunluk biriktirir. Şırnak'ta rahatlama ve dinlenme masajı ile kaslarınızı gevşetiyor, zihninizi dinlendiriyoruz. Bir yere gitmenize gerek yok; randevu saatinde evinize geliyoruz.",
  what="Rahatlama masajı, orta basınçla ve ritmik hareketlerle tüm vücuda uygulanan klasik bir masajdır. Amaç ağrı tedavisi değil, kas gerginliğini azaltmak, kan dolaşımını desteklemek ve kişinin kendini dinlenmiş hissetmesini sağlamaktır.",
  **{"for":["Stresli ve yoğun çalışan herkes","Uyku düzeni bozulan, yorgun uyanan kişiler","Uzun süre ayakta veya masa başında çalışanlar","Haftalık rutinine dinlenme eklemek isteyenler"]},
  steps=["Randevu saatinde evinize geliyoruz","Kısa bir görüşmeyle şikâyetlerinizi ve tercihlerinizi soruyoruz","Masaj alanını hazırlıyoruz","Sırt, boyun, omuz, kol ve bacaklara rahatlatıcı masaj uyguluyoruz","Seans sonunda dinlenmeniz için öneriler veriyoruz"],
  tips=["Masajdan hemen önce ağır yemek yemeyin","Seans sonrası bol su için","Masajdan sonra birkaç saat ağır egzersiz yapmayın","Basınç tercihinizi seans sırasında söyleyin"],
  faqs=[("Rahatlama masajı ne kadar sürer?","Seans süresi ihtiyacınıza göre belirlenir; randevu sırasında birlikte planlıyoruz."),
        ("Masaj için evde ne hazırlamam gerekir?","Sessiz bir oda ve uzanabileceğiniz bir alan yeterlidir; gerekli malzemeleri biz getiriyoruz."),
        ("Dinlenme masajı ile rahatlama masajı aynı mı?","Evet, ikisi de aynı amaca yöneliktir: kasları gevşetmek ve dinlendirmek."),
        ("Hangi ilçelere geliyorsunuz?","Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'a geliyoruz.")]),
 dict(slug="bel-fitigi-masaji", name="Bel Fıtığı Masajı", kw="Bel Fıtığı Masajı",
  intro="Bel fıtığı yaşayan birçok kişi bel çevresindeki kas sertliği ve gerginlikten şikâyet eder. Şırnak'ta bel fıtığı masajı ile bel, kalça ve sırt bölgesindeki kasları gevşetmeye yönelik, nazik ve kontrollü teknikler uyguluyoruz. Halk arasında fıtıkçı olarak bilinen geleneksel masaj yaklaşımını, adresinize gelerek sunuyoruz.",
  what="Bel fıtığı masajı, fıtığı yerine 'oturtan' bir işlem değil; fıtığa eşlik eden kas spazmını ve gerginliği azaltmaya yönelik destekleyici bir masajdır. Bel çevresindeki kasların gevşemesi, hareket ederken hissedilen sertliğin azalmasına yardımcı olabilir.",
  **{"for":["Doktor tarafından bel fıtığı tanısı konmuş ve masaja engel durumu olmayanlar","Bel ve kalça çevresinde kas sertliği hissedenler","Uzun süre oturarak veya ağır kaldırarak çalışanlar"]},
  caution=DOCTOR,
  steps=["Şikâyetinizi, varsa doktor raporunuzu ve ağrının yerini soruyoruz","Uygun pozisyonda, beli zorlamadan çalışıyoruz","Bel, kalça ve sırt kaslarına nazik basınçla masaj uyguluyoruz","Ağrı artarsa uygulamayı hemen durduruyoruz","Günlük hayatta beli korumanız için öneriler veriyoruz"],
  tips=["Masaj sonrası ani eğilme ve ağır kaldırmadan kaçının","Uzun süre aynı pozisyonda oturmayın","Doktorunuzun önerdiği egzersizleri sürdürün","Ağrınız artarsa doktorunuza başvurun"],
  faqs=[("Bel fıtığı masajla geçer mi?","Masaj bel fıtığını tedavi etmez. Fıtığa eşlik eden kas gerginliğini azaltarak rahatlamanıza yardımcı olabilir; tedavi için doktorunuzun önerilerine uyun."),
        ("Bel fıtığı ameliyatı olan masaj yaptırabilir mi?","Ameliyat sonrası masaj için mutlaka doktorunuzun onayını almalısınız."),
        ("Fıtıkçı ile masör arasında fark var mı?","Şırnak'ta halk arasında fıtıkçı denince bel ve boyun şikâyetleri için geleneksel masaj yapan kişi anlaşılır. Biz bu masajı tıbbi tedavi iddiası olmadan, destekleyici olarak uyguluyoruz."),
        ("Hangi durumlarda bel fıtığı masajı yapılmaz?","Bacakta güç kaybı, uyuşma, idrar veya dışkı kontrolünde sorun, ateş veya yakın zamanda geçirilmiş bir travma varsa masaj yapılmaz; doktora başvurulmalıdır."),
        ("Evime gelir misiniz?","Evet, seyyar çalışıyoruz; Şırnak'ın tüm ilçelerinde adresinize geliyoruz.")]),
 dict(slug="boyun-fitigi-masaji", name="Boyun Fıtığı Masajı", kw="Boyun Fıtığı Masajı",
  intro="Boyun fıtığı olan kişilerde boyun, ense ve omuz kasları sıklıkla gerilir; baş ağrısı ve omuzlarda ağırlık hissi buna eşlik edebilir. Şırnak'ta boyun fıtığı masajı ile bu bölgedeki kas gerginliğini azaltmaya yönelik nazik bir masaj uyguluyoruz.",
  what="Boyun fıtığı masajı, boyun omurlarına baskı uygulamadan, çevresindeki kaslara yönelik yumuşak tekniklerle yapılan destekleyici bir masajdır. Ani çekme veya çıtlatma hareketleri yapılmaz.",
  **{"for":["Boyun fıtığı tanısı olan ve doktorunun masaja engel görmediği kişiler","Masa başında, telefon ve bilgisayarla uzun süre çalışanlar","Ense ve omuzlarında sürekli gerginlik hissedenler"]},
  caution=DOCTOR,
  steps=["Şikâyetlerinizi ve ağrının yayıldığı bölgeleri soruyoruz","Uygun pozisyonda boynu zorlamadan çalışıyoruz","Ense, omuz ve sırt üst bölgesine nazik masaj uyguluyoruz","Seans sonunda duruş ve günlük kullanım önerileri veriyoruz"],
  tips=["Telefonu göz hizasında kullanmaya çalışın","Uzun süre aynı pozisyonda kalmayın, ara verin","Uygun yükseklikte yastık kullanın","Kolda uyuşma veya güç kaybı varsa doktora başvurun"],
  faqs=[("Boyun fıtığı masajı acıtır mı?","Uygulama nazik yapılır; rahatsızlık hissederseniz basıncı azaltıyor veya duruyoruz."),
        ("Boyun fıtığında boyun çıtlatılır mı?","Hayır. Boyunda ani çekme ve çıtlatma hareketleri yapmıyoruz."),
        ("Boyun fıtığı masajla iyileşir mi?","Masaj tedavi değildir; kas gerginliğini azaltarak rahatlamanıza yardımcı olabilir."),
        ("Hangi ilçelere geliyorsunuz?","Şırnak'ın tüm ilçelerinde evinize geliyoruz.")]),
 dict(slug="boyun-duzlesmesi-masaji", name="Boyun Düzleşmesi Masajı", kw="Boyun Düzleşmesi Masajı",
  intro="Boyun düzleşmesi, boyun omurlarının doğal kavisinin azalmasıdır ve genellikle ense ile omuzlarda sertlik, baş ağrısı ve çabuk yorulma ile kendini gösterir. Şırnak'ta boyun düzleşmesi masajı ile boyun ve omuz kaslarındaki sertliği gevşetmeye yönelik destekleyici bir masaj uyguluyoruz.",
  what="Boyun düzleşmesinde boyun çevresindeki kaslar sürekli gergin çalışır. Bu masaj, ense, omuz ve sırt üst bölgesindeki kasları gevşetmeye odaklanır; omurların yapısını değiştirme iddiası taşımaz.",
  **{"for":["Boyun düzleşmesi tanısı olanlar","Uzun süre telefon ve bilgisayar kullananlar","Ense ve omuzlarında sürekli ağırlık hissedenler"]},
  caution=DOCTOR,
  steps=["Şikâyetlerinizi ve günlük duruşunuzu soruyoruz","Ense, omuz ve kürek kemiği çevresine nazik masaj uyguluyoruz","Boyna ani hareket yaptırmadan çalışıyoruz","Duruş ve günlük kullanım önerileri veriyoruz"],
  tips=["Ekranı göz hizasına getirin","Saatte bir kısa esneme molası verin","Doktorunuzun veya fizyoterapistinizin önerdiği egzersizleri yapın"],
  faqs=[("Boyun düzleşmesi masajla düzelir mi?","Masaj boyun kavisini düzeltmez; kas gerginliğini azaltarak rahatlamanıza yardımcı olabilir."),
        ("Ne sıklıkla masaj yaptırmalıyım?","Bu, şikâyetinize göre değişir; ilk seansta birlikte değerlendiriyoruz."),
        ("Evime gelir misiniz?","Evet, Şırnak'ın tüm ilçelerinde adresinize geliyoruz.")]),
 dict(slug="kuyruk-sokumu-masaji", name="Kuyruk Sokumu Masajı", kw="Kuyruk Sokumu Masajı",
  intro="Kuyruk sokumu ve bel altı bölgesindeki ağrı, uzun süre oturmakla veya oturup kalkarken artabilir. Şırnak'ta kuyruk sokumu masajı ile bu bölgedeki ve çevresindeki kas gerginliğini azaltmaya yönelik rahatlatıcı bir masaj uyguluyoruz.",
  what="Kuyruk sokumu masajı, kuyruk sokumu çevresindeki kalça ve bel altı kaslarına yönelik, nazik basınçla uygulanan bir masajdır.",
  **{"for":["Uzun süre oturarak çalışanlar","Bel altı ve kalça bölgesinde gerginlik hissedenler","Doktorunun masaja engel görmediği kuyruk sokumu ağrısı olanlar"]},
  caution="Önemli: Düşme veya darbe sonrası başlayan kuyruk sokumu ağrısında, kırık veya çatlak ihtimaline karşı önce doktora başvurun. Masaj tıbbi tedavinin yerine geçmez.",
  steps=["Ağrının ne zaman ve nasıl başladığını soruyoruz","Uygun pozisyonda, bölgeye doğrudan sert baskı yapmadan çalışıyoruz","Kalça ve bel altı kaslarına rahatlatıcı masaj uyguluyoruz","Oturma ve günlük kullanım önerileri veriyoruz"],
  tips=["Uzun süre sert zeminde oturmaktan kaçının","Oturduğunuzda ara ara kalkıp yürüyün","Ağrı artarsa doktorunuza danışın"],
  faqs=[("Kuyruk sokumu masajı nasıl yapılır?","Kuyruk sokumu çevresindeki kalça ve bel altı kaslarına nazik basınçla yapılır."),
        ("Düştükten sonra kuyruk sokumum ağrıyor, masaj olur mu?","Önce doktora görünmenizi öneririz; kırık veya çatlak yoksa ve doktorunuz uygun görürse masaj yapılabilir."),
        ("Evime gelir misiniz?","Evet, Şırnak'ın tüm ilçelerinde adresinize geliyoruz.")]),
 dict(slug="gobek-dusmesi", name="Göbek Düşmesi (Göbek Oturtma)", kw="Göbek Düşmesi",
  intro="Halk arasında göbek düşmesi, göbek kayması ya da göbek kaçması olarak bilinen durumda kişiler karın ağrısı, şişkinlik ve halsizlik gibi şikâyetlerden bahseder. Şırnak'ta göbek oturtma geleneksel yöntemle, karın bölgesine nazik masaj şeklinde uygulanır.",
  what="Göbek düşmesi tıp literatüründe tanımlı bir hastalık değildir; Anadolu'da kuşaktan kuşağa aktarılan geleneksel bir kavramdır. Göbek oturtma uygulaması, karın bölgesine yapılan rahatlatıcı bir masajdır. Göbek fıtığı ile karıştırılmamalıdır: göbek fıtığında göbek çevresinde şişlik olur ve doktor kontrolü gerekir.",
  **{"for":["Geleneksel göbek oturtma uygulamasını tercih edenler","Karın bölgesinde gerginlik hissedip doktor kontrolünde ciddi bir sorunu olmayanlar"]},
  caution="Önemli: Şiddetli veya geçmeyen karın ağrısı, ateş, kusma, kanama ya da göbek çevresinde şişlik varsa masaj yerine hemen doktora başvurun. Hamilelerde karın bölgesine bu uygulama yapılmaz.",
  steps=["Şikâyetlerinizi ve ne zaman başladığını soruyoruz","Ciddi bir belirti varsa doktora yönlendiriyoruz","Uygun pozisyonda karın bölgesine nazik masaj uyguluyoruz","Seans sonrası dinlenmeniz için öneriler veriyoruz"],
  tips=["Uygulamadan önce ağır yemek yemeyin","Uygulama sonrası ağır kaldırmaktan kaçının","Şikâyetleriniz sürerse doktora başvurun"],
  faqs=[("Göbek düşmesi gerçekten var mı?","Göbek düşmesi tıbbi bir tanı değil, geleneksel bir kavramdır. Karın ağrısının birçok farklı sebebi olabileceği için şikâyetiniz sürüyorsa doktora başvurmalısınız."),
        ("Göbek oturtma acıtır mı?","Uygulama nazik yapılır; rahatsızlık hissederseniz duruyoruz."),
        ("Göbek düşmesi ile göbek fıtığı aynı şey mi?","Hayır. Göbek fıtığında göbek çevresinde şişlik olur ve tedavisi doktor tarafından yapılır."),
        ("Evime gelir misiniz?","Evet, Şırnak'ın tüm ilçelerinde adresinize geliyoruz.")]),
 dict(slug="kulunc-masaji", name="Kulunç Masajı", kw="Kulunç Masajı",
  intro="Sırtta, kürek kemiği çevresinde veya omuzda ele gelen sert ve ağrılı noktalara halk arasında kulunç denir. Şırnak'ta kulunç masajı ile bu kas düğümlerini açmaya yönelik geleneksel masaj uyguluyoruz. Eve gelen masör olarak adresinize geliyoruz.",
  what="Kulunç, genellikle uzun süre aynı pozisyonda kalmak, soğuk almak veya ağır kaldırmak sonrasında kaslarda oluşan sertlik ve düğümlenmedir. Kulunç masajı, bu noktalara kontrollü basınç ve ovma hareketleriyle uygulanır.",
  **{"for":["Sırtında ve omzunda kulunç ağrısı olanlar","Masa başında çalışanlar","Ağır kaldırarak çalışanlar","Soğuk aldıktan sonra sırtı tutulanlar"]},
  steps=["Ağrının yerini ve ne zaman başladığını soruyoruz","Kulunç noktalarını elle tespit ediyoruz","Bu noktalara kontrollü basınç ve masaj uyguluyoruz","Çevre kasları da gevşeterek seansı tamamlıyoruz"],
  tips=["Masaj sonrası sırtınızı sıcak tutun","Soğuk havada sırtınızı açıkta bırakmayın","Uzun süre aynı pozisyonda kalmayın"],
  faqs=[("Kulunç neden olur?","Uzun süre aynı pozisyonda kalmak, soğuk almak, stres ve ağır kaldırmak kulunç oluşmasına yol açabilir."),
        ("Kulunç masajı acıtır mı?","Kulunç noktalarına basınç uygulanırken hafif bir hassasiyet olabilir; basıncı size göre ayarlıyoruz."),
        ("Kaç seansta kulunç açılır?","Bu kişiden kişiye değişir; birçok kişi ilk seanstan sonra rahatladığını söyler."),
        ("Evime gelir misiniz?","Evet, Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'ta evinize geliyoruz.")]),
 dict(slug="hamile-masaji", name="Hamile Masajı", kw="Hamile Masajı",
  intro="Hamilelikte artan kilo ve değişen duruş bel, sırt ve bacaklarda yorgunluğa yol açar. Şırnak'ta hamile masajı ile bu yorgunluğu hafifletmeye yönelik, güvenli pozisyonlarda ve nazik tekniklerle masaj uyguluyoruz. Evinizin rahatlığında, adresinize gelerek hizmet veriyoruz.",
  what="Hamile masajı, anne adayının yan yatar veya destekli oturur pozisyonda olduğu, karın bölgesine baskı yapılmayan, hafif basınçlı bir masajdır.",
  **{"for":["Doktorunun onay verdiği anne adayları","Bel, sırt ve bacaklarda yorgunluk hissedenler","Genellikle ilk üç aydan sonraki dönemde olanlar"]},
  caution="Önemli: Hamile masajından önce mutlaka doktorunuzun onayını alın. Riskli gebelik, kanama, yüksek tansiyon, bacakta şişlik ve ağrı (pıhtı şüphesi) gibi durumlarda masaj yapılmaz.",
  steps=["Gebelik haftanızı ve doktor onayınızı soruyoruz","Yan yatar veya destekli pozisyonda çalışıyoruz","Bel, sırt, omuz ve bacaklara hafif basınçla masaj uyguluyoruz","Karın bölgesine uygulama yapmıyoruz"],
  tips=["Masaj öncesi ve sonrası bol su için","Kendinizi rahatsız hissederseniz hemen söyleyin","Doktor kontrollerinizi aksatmayın"],
  faqs=[("Hamileyken masaj yaptırmak güvenli mi?","Doktorunuzun onay verdiği durumlarda, uygun pozisyon ve hafif basınçla yapılan masaj genellikle güvenli kabul edilir."),
        ("Hamilelikte hangi ayda masaj yapılır?","Genellikle ilk üç aydan sonra önerilir; doktorunuza danışarak karar verin."),
        ("Karına masaj yapılır mı?","Hayır, hamile masajında karın bölgesine uygulama yapmıyoruz."),
        ("Evime gelir misiniz?","Evet, Şırnak'ın tüm ilçelerinde evinize geliyoruz.")]),
]

def _m(slug, name, kw, intro, what, for_, steps, tips, faqs, caution=""):
    return dict(slug=slug, name=name, kw=kw, intro=intro, what=what, caution=caution,
                steps=steps, tips=tips, faqs=faqs, **{"for": for_})

_EV = ("Evime gelir misiniz?", "Evet, seyyar çalışıyoruz; Şırnak Merkez, Cizre, Silopi, İdil, Beytüşşebap, Uludere ve Güçlükonak'ta adresinize geliyoruz.")
_SURE = ("Seans ne kadar sürer?", "Seans süresi ihtiyacınıza göre belirlenir; randevu sırasında birlikte planlıyoruz.")

M += [
 _m("boyun-sirt-masaji","Boyun ve Sırt Masajı","Boyun ve Sırt Masajı",
  "Gün boyu masa başında oturmak, telefona eğilmek ya da ağır iş yapmak boyun ve sırtta sertlik ve ağrı bırakır. Şırnak'ta boyun ve sırt masajı ile ense, omuz ve sırt kaslarındaki gerginliği gevşetiyoruz. Bir yere gitmenize gerek yok, randevu saatinde evinize geliyoruz.",
  "Boyun ve sırt masajı; ense, omuz, kürek kemikleri çevresi ve bel üstüne odaklanan bölgesel bir masajdır. Tüm vücut masajına göre daha kısa sürer ve gerginliğin en çok biriktiği bölgeye yoğunlaşır.",
  ["Masa başında, bilgisayar ve telefonla uzun süre çalışanlar","Ense ve omuzlarında sürekli ağırlık hissedenler","Şoförler ve ağır iş yapanlar","Stres nedeniyle omuzları kasılanlar"],
  ["Ağrının ve gerginliğin yerini soruyoruz","Ense ve omuzlardan başlayarak sırta doğru çalışıyoruz","Sert noktalara kontrollü basınç uyguluyoruz","Seans sonunda duruş önerileri veriyoruz"],
  ["Ekranı göz hizasında tutun","Saatte bir kısa esneme molası verin","Masaj sonrası boynunuzu soğuktan koruyun"],
  [("Boyun ve sırt masajı baş ağrısına iyi gelir mi?","Kas gerginliğinden kaynaklanan baş ağrılarında rahatlama sağlayabilir; sık ve şiddetli baş ağrısında doktora başvurun."), _SURE, _EV]),
 _m("isvec-masaji","İsveç Masajı","İsveç Masajı",
  "İsveç masajı, dünyada en çok bilinen klasik masaj tekniğidir. Şırnak'ta İsveç masajı ile tüm vücuda uzun, akıcı hareketlerle rahatlatıcı bir masaj uyguluyoruz. Evinizin rahatlığında, adresinize gelerek hizmet veriyoruz.",
  "İsveç masajında uzun sıvazlama, yoğurma, ovma ve hafif vurma hareketleri kullanılır. Amaç kasları gevşetmek, dolaşımı desteklemek ve genel bir rahatlama sağlamaktır. Basınç orta düzeydedir ve kişiye göre ayarlanır.",
  ["İlk kez masaj yaptıracaklar","Genel yorgunluk ve stres yaşayanlar","Düzenli rahatlama masajı isteyenler"],
  ["Tercih ettiğiniz basıncı soruyoruz","Sırt, bacak, kol, omuz ve boyun bölgelerine sırayla masaj uyguluyoruz","Uzun ve ritmik hareketlerle kasları gevşetiyoruz","Seansı rahatlatıcı hareketlerle tamamlıyoruz"],
  ["Masaj öncesi ağır yemek yemeyin","Seans sonrası bol su için","Basıncı seans sırasında istediğiniz gibi değiştirebilirsiniz"],
  [("İsveç masajı ile klasik masaj aynı mı?","Evet, İsveç masajı genellikle klasik masaj olarak da anılır."), _SURE, _EV]),
 _m("kas-masaji","Kas Masajı","Kas Masajı",
  "Ağır iş, spor ya da uzun süre ayakta kalmak kaslarda yorgunluk ve sertlik bırakır. Şırnak'ta kas masajı ile yorgun ve gergin kasları derinlemesine gevşetiyoruz. Seyyar çalışıyor, evinize geliyoruz.",
  "Kas masajı, yorgun ve sertleşmiş kas gruplarına yoğunlaşan, orta ve güçlü basınçla yapılan bir masajdır. Kas spazmı ve sertlik hissinin azalmasına yardımcı olabilir.",
  ["Ağır fiziksel iş yapanlar","Spor sonrası kas yorgunluğu yaşayanlar","Bacak ve sırt kaslarında sertlik hissedenler"],
  ["Hangi kaslarda yorgunluk olduğunu soruyoruz","Isıtıcı hareketlerle kasları hazırlıyoruz","Sert bölgelere derinlemesine masaj uyguluyoruz","Rahatlatıcı hareketlerle bitiriyoruz"],
  ["Masaj sonrası bol su için","Aynı gün ağır antrenmandan kaçının","Hafif esneme hareketleri yapın"],
  [("Kas masajı acıtır mı?","Basınç güçlü olabilir ama rahatsız edici olmamalı; basıncı size göre ayarlıyoruz."), _SURE, _EV]),
 _m("aromaterapi","Aromaterapi Masajı","Aromaterapi Masajı",
  "Aromaterapi masajı, doğal uçucu yağların hoş kokusuyla birleşen rahatlatıcı bir masajdır. Şırnak'ta aromaterapi masajını evinizin huzurlu ortamında uyguluyoruz.",
  "Bu masajda taşıyıcı yağlarla seyreltilmiş doğal uçucu yağlar kullanılır. Hafif ve orta basınçlı hareketlerle uygulanır; amaç zihinsel ve bedensel rahatlamadır.",
  ["Stresli ve yorgun hissedenler","Hafif basınçlı, rahatlatıcı masaj sevenler","Uyku öncesi rahatlamak isteyenler"],
  ["Yağ ve koku tercihinizi, varsa alerjilerinizi soruyoruz","Seçilen yağla tüm vücuda hafif masaj uyguluyoruz","Nefes ve rahatlamaya odaklanan ritimle çalışıyoruz"],
  ["Bilinen bir alerjiniz varsa mutlaka söyleyin","Masaj sonrası yağın cildinizde bir süre kalmasına izin verin","Hamileyseniz uçucu yağ kullanımı için doktorunuza danışın"],
  [("Hangi yağlar kullanılıyor?","Doğal uçucu yağları taşıyıcı yağlarla seyrelterek kullanıyoruz; tercihinizi ve alerjilerinizi önceden soruyoruz."), _SURE, _EV]),
 _m("sicak-tas","Sıcak Taş Masajı","Sıcak Taş Masajı",
  "Sıcak taş masajında ısıtılmış pürüzsüz taşlar, masajla birlikte kaslara sıcaklık vererek derin bir gevşeme sağlar. Şırnak'ta sıcak taş masajını gerekli ekipmanla evinize gelerek uyguluyoruz.",
  "Isıtılmış taşlar vücudun belirli noktalarına yerleştirilir ve masaj sırasında da kullanılır. Sıcaklık kasların gevşemesine yardımcı olur.",
  ["Kaslarında sertlik hissedenler","Soğuk havalarda üşüyen, gevşemekte zorlananlar","Derin rahatlama isteyenler"],
  ["Sağlık durumunuzu ve sıcaklık hassasiyetinizi soruyoruz","Taşları uygun sıcaklığa getiriyoruz","Taşları yerleştirip masajla birlikte kullanıyoruz","Sıcaklığı sürekli kontrol ediyoruz"],
  ["Diyabet, dolaşım bozukluğu veya cilt hassasiyetiniz varsa önceden söyleyin","Hamilelikte sıcak taş masajı yapılmaz","Seans sonrası bol su için"],
  [("Sıcak taş masajı yakar mı?","Taşların sıcaklığını kontrol ederek uyguluyoruz; fazla sıcak gelirse hemen söyleyin."), _SURE, _EV]),
 _m("refleksoloji","Refleksoloji","Refleksoloji",
  "Refleksoloji, ayak tabanı ve ellerdeki belirli noktalara uygulanan basınçla yapılan geleneksel bir masaj yöntemidir. Şırnak'ta refleksolojiyi evinizde, rahat bir ortamda uyguluyoruz.",
  "Refleksolojide ayak ve ellerdeki noktalara parmaklarla basınç uygulanır. Ayakta biriken yorgunluğu almak ve genel rahatlama sağlamak için tercih edilir.",
  ["Uzun süre ayakta kalanlar","Ayaklarında yorgunluk ve ağırlık hissedenler","Tüm vücut masajı yerine ayak masajı tercih edenler"],
  ["Ayakları ısıtıcı hareketlerle hazırlıyoruz","Ayak tabanı ve çevresine noktasal basınç uyguluyoruz","Basıncı size göre ayarlıyoruz"],
  ["Ayakta açık yara veya enfeksiyon varsa uygulama yapılmaz","Seans sonrası bol su için"],
  [("Refleksoloji hastalık tedavi eder mi?","Refleksoloji tıbbi bir tedavi değildir; rahatlama amaçlı uygulanır."), _SURE, _EV]),
 _m("bitkisel-yag","Bitkisel Yağ Terapisi","Bitkisel Yağ Masajı",
  "Bitkisel yağ terapisi, doğal bitkisel yağlarla yapılan, cildi besleyen ve rahatlatan bir masajdır. Şırnak'ta bu masajı evinize gelerek uyguluyoruz.",
  "Masajda zeytinyağı, badem yağı gibi doğal bitkisel yağlar kullanılır. Yağ cildi nemlendirirken masaj hareketleri kasları gevşetir.",
  ["Cildi kuru olanlar","Doğal yağlarla masaj tercih edenler","Rahatlatıcı tüm vücut masajı isteyenler"],
  ["Yağ tercihinizi ve alerjilerinizi soruyoruz","Yağı ısıtarak tüm vücuda masaj uyguluyoruz","Hafif ve orta basınçla çalışıyoruz"],
  ["Alerjiniz varsa önceden söyleyin","Masaj sonrası duş için birkaç saat bekleyebilirsiniz"],
  [("Hangi yağlar kullanılıyor?","Doğal bitkisel yağlar kullanıyoruz; tercihinizi ve alerjilerinizi önceden soruyoruz."), _SURE, _EV]),
 _m("spor-masaji","Spor Masajı","Spor Masajı",
  "Spor masajı, düzenli spor yapanların kas yorgunluğunu azaltmak ve esnekliğini desteklemek için uygulanan bir masajdır. Şırnak'ta spor masajını antrenman programınıza uygun saatte evinize gelerek uyguluyoruz.",
  "Spor masajında, sporun türüne göre en çok çalışan kas gruplarına odaklanılır. Antrenman öncesi hazırlayıcı, sonrası ise toparlayıcı olarak uygulanabilir.",
  ["Düzenli spor yapanlar","Futbol, koşu, fitness gibi branşlarla ilgilenenler","Antrenman sonrası kas yorgunluğu yaşayanlar"],
  ["Spor türünüzü ve yorgun kas gruplarını soruyoruz","Isıtıcı hareketlerle başlıyoruz","Hedef kaslara derinlemesine masaj uyguluyoruz","Esneme önerileriyle bitiriyoruz"],
  ["Sakatlık varsa önce doktor veya fizyoterapiste görünün","Masaj sonrası bol su için"],
  [("Spor masajı sakatlığı iyileştirir mi?","Spor masajı sakatlık tedavisi değildir; yeni bir sakatlıkta önce doktora başvurun."), _SURE, _EV]),
 _m("derin-doku","Derin Doku Masajı","Derin Doku Masajı",
  "Derin doku masajı, kasların derin katmanlarına yavaş ve güçlü basınçla uygulanan bir masajdır. Şırnak'ta derin doku masajı ile uzun süredir devam eden kas sertliğini gevşetmeye çalışıyoruz. Evinize geliyoruz.",
  "Derin doku masajında yüzeysel kaslardan çok, alttaki kas katmanlarına ve bağ dokusuna yavaş, güçlü basınç uygulanır. Kronik kas gerginliğinde tercih edilir.",
  ["Uzun süredir kas sertliği yaşayanlar","Güçlü basınçlı masaj sevenler","Ağır iş yapanlar"],
  ["Sertliğin yerini ve basınç tercihinizi soruyoruz","Yüzeysel hareketlerle kasları ısıtıyoruz","Sert bölgelere yavaş ve güçlü basınç uyguluyoruz","Rahatlatıcı hareketlerle bitiriyoruz"],
  ["Masajdan sonraki gün hafif kas hassasiyeti normaldir","Bol su için","Kan sulandırıcı kullanıyorsanız önceden söyleyin"],
  [("Derin doku masajı acıtır mı?","Basınç güçlüdür ama dayanılmaz olmamalı; rahatsızlık hissederseniz hemen azaltıyoruz."), _SURE, _EV]),
]

def sql_lit(s): return "'" + s.replace("'", "''") + "'"

def build(site):
    rows = T if site == "tesisat" else M
    fn = tesisat if site == "tesisat" else masaj
    out = ["begin;"]
    for s in rows:
        faqs = json.dumps([{"q": q, "a": a} for q, a in s["faqs"]], ensure_ascii=False)
        out.append(f"update services set content={sql_lit(fn(s))}, faqs={sql_lit(faqs)}::jsonb where slug='{s['slug']}' and site_id=(select id from sites where slug='{site}');")
    out.append("commit;")
    return "\n".join(out)

if __name__ == "__main__":
    print(build(sys.argv[1]))
