[build]
  command = "cd ../.. && npm ci --legacy-peer-deps && npm run build --workspace=apps/admin"
  publish = ".next"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
